---
- hosts: flightcontrollers
  vars:
    python_version: 3.6.4
  tasks:
    - name: update && upgrade
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: install build environment
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
        - build-essential
        - checkinstall
        - libreadline-gplv2-dev
        - libncursesw5-dev
        - libssl-dev
        - libsqlite3-dev
        - tk-dev
        - libgdbm-dev
        - libc6-dev
        - libbz2-dev

    - name: fetching source
      unarchive:
        src: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
        dest: "/tmp"
        remote_src: yes

    - name: installing python (takes like 30 minutes)
      command: "{{ item }}"
      args:
        chdir: "/tmp/Python-{{ python_version }}"
      with_items:
        - ./configure
        - make
        - make install

    - name: uninstall build environment
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - build-essential
        - checkinstall
        - libreadline-gplv2-dev
        - libncursesw5-dev
        - libssl-dev
        - libsqlite3-dev
        - tk-dev
        - libgdbm-devr
        - libc6-dev
        - libbz2-dev

    - file:
        state: absent
        path: "/tmp/Python-{{ python_version }}"
