---
- hosts: currants
  vars:
    python_version: 3.9.5
    build_environment:
      - build-essential
      - tk-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline6-dev
      - libdb5.3-dev
      - libgdbm-dev
      - libsqlite3-dev
      - libssl-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - zlib1g-dev
      - libffi-dev
      - libc-dev

  tasks:
    - name: update && upgrade
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: install build environment
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ build_environment }}"

    - name: fetching source
      unarchive:
        src: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
        dest: "/tmp"
        remote_src: yes

    - name: installing python (takes like 30-40 minutes)
      command: "{{ item }}"
      args:
        chdir: "/tmp/Python-{{ python_version }}"
      with_items:
        - ./configure
        - make
        - make install

    - name: uninstall build environment
      apt:
        name: "{{ item }}"
        state: absent
      with_items: "{{ build_environment }}"

    - file:
        state: absent
        path: "/tmp/Python-{{ python_version }}"

    # set python3 as the default
    - file:
        src: "/usr/local/bin/{{ item }}3"
        dest: "/usr/bin/{{ item }}"
        state: link
      with_items:
        - python
        - pip
