# ANSIBLE_CONFIG=./ansible.cfg ansible-playbook setup.yml
---
- hosts: currants
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"

  - name: remove the default user
    user:
      name: pi
      state: absent
      remove: yes

  - apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - git
      - python3-smbus
      - python3-dev
      - python3-pip
      - python3-setuptools
      - dnsmasq
      - hostapd
    tags: [packages, apt]

  # TODO: why is this failing?
  # - pip:
  #     name: pipenv
  #     executable: pip3
  #   tags: [pip]

  - file:
      path: /opt/currant
      state: directory
      mode: 0755

  # one day we maybe we'll deploy this way
  # - git:
  #     repo: git@gitlab.com:b1tzky/currant.git
  #     dest: /tmp/currant
  #     depth: 1

  # - copy:
  #     src: /tmp/currant/currant
  #     dest: /opt/currant
  #     remote_src: yes

  # - name: configure systemd service
  #   copy:
  #     src: currant.service
  #     dest: /etc/systemd/system/currant.service
  #     owner: root
  #     group: root
  #     mode: 0644
  #   notify: [systemd]
  #   tags: [systemd]

  - name: dhcp
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: "dnsmasq.conf", dest: "/etc/dnsmasq.conf" }
      - { src: "dhcpcd.conf", dest: "/etc/dhcpcd.conf" }
    notify: [dnsmasq]
    tags: [dhcp, wifi]

  - name: hostapd
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: "hostapd", dest: "/etc/default/" }
      - { src: "hostapd.conf", dest: "/etc/hostapd/" }
    notify: [hostapd]
    tags: [hostapd, wifi]

  - name: interfaces
    copy:
      src: interfaces
      dest: /etc/network/
      owner: root
      group: root
      mode: 0644
    notify: [networking]
    tags: [interfaces, wifi]

  - name: install preflight
    copy:
      src: preflight
      dest: /usr/local/bin/
      owner: root
      group: staff
      mode: a+x
    tags: [preflight]

  handlers:
    # - name: systemd
    #   systemd:
    #     name: currant
    #     daemon_reload: yes
    #     enabled: yes
    #     state: restarted

    - name: dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

    - name: networking
      systemd:
        name: networking
        enabled: yes
        state: restarted

    - name: hostapd
      systemd:
        name: hostapd
        enabled: yes
        state: restarted
