---
- hosts: flightcontrollers
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"

  - name: remove the default user
    user:
      name: pi
      state: absent
      remove: yes

  - name: clear motd
    copy:
      content: ""
      dest: /etc/motd
      force: yes
      group: root
      owner: root
      mode: 0644

  - apt:
      name: "{{ item }}"
      state: installed
    with_items:
      - vim
      - python3-smbus
      - python3-dev
      - python3-setuptools
      # - xboxdrv
      - dnsmasq
      - hostapd
    tags: [packages, apt]

  - pip:
      name: pipenv
      executable: pip3
    tags: [pip]

  - file:
      path: /opt/flightcontroller
      state: directory
      mode: 0755

  # - name: configure xboxdrv
  #   copy:
  #     src: xboxdrv.service
  #     dest: /etc/systemd/system/xboxdrv.service
  #     owner: root
  #     group: root
  #     mode: 0644
  #   notify: [xboxdrv]
  #   tags: [xboxdrv]

  # - modprobe:
  #     name: xpad
  #     state: absent
  #   tags: [xboxdrv]

  # - name: blacklist xpad driver
  #   kernel_blacklist:
  #     name: xpad
  #     state: present
  #   tags: [xboxdrv]

  - name: dhcp
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: "dnsmasq.conf", dest: "/etc/dnsmasq.conf" }
      - { src: "dhcpcd.conf", dest: "/etc/dhcpcd.conf" }
    notify: [dnsmasq]
    tags: [dhcp, wifi]

  - name: hostapd
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: "hostapd", dest: "/etc/default/" }
      - { src: "hostapd.conf", dest: "/etc/hostapd/" }
    notify: [hostapd]
    tags: [hostapd, wifi]

  - name: interfaces
    copy:
      src: interfaces
      dest: /etc/network/
      owner: root
      group: root
      mode: 0644
    notify: [networking]
    tags: [interfaces, wifi]

  - name: install preflight
    copy:
      src: preflight
      dest: /usr/local/bin/
      owner: root
      group: staff
      mode: a+x
    tags: [preflight]

  handlers:
    # - name: xboxdrv
    #   systemd:
    #     name: xboxdrv
    #     daemon_reload: yes
    #     enabled: yes
    #     state: restarted

    - name: dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

    - name: networking
      systemd:
        name: networking
        enabled: yes
        state: restarted

    - name: hostapd
      systemd:
        name: hostapd
        enabled: yes
        state: restarted
